### PR TITLE
Pulling updates

### PR DESCRIPTION
**Pull request by Kneckter**
I have a local copy of the code if anything goes wrong with the pull.

### CODE REVIEW

**Comment by Kneckter** [comment]
Only the barbarian village code (f15635c) needs to be added to your code. The others can be rejected.

**Comment by JohnRThomas** [comment]
I had to rebase my repository since commit fbe278b git a weird author somehow (I honestly have no idea how that happened).

Can you make a fresh repository and remake the changes to that file? Otherwise that commit goes back into the history.

Sorry about that.

**Comment by JohnRThomas** [comment]
Never mind about making a new pull request. I figured out how to cherry pick so that you are still the author of the commit.

I would suggest making a clean repo, or at lead reverting your head to the head of my repo so that the extra commit history is rightfully ignored.

Thanks

**Comment by Kneckter** [comment]
I couldn't figure out how to clean it up. So I deleted it reforked haha.

**Comment by JohnRThomas** [comment]
Sounds good. Sorry about that.

**Pull request closed without merging**
